# Generated by Django 3.0 on 2019-12-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191225_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_tech_stack',
            field=models.CharField(max_length=255),
        ),
    ]
