# Generated by Django 3.0 on 2019-12-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191225_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[(1, 'Advanced'), (2, 'Intermidate'), (3, 'Beginner')], default=3, max_length=32)),
                ('profile', models.ManyToManyField(null=True, to='core.Profile')),
            ],
        ),
    ]
