# Generated by Django 3.0 on 2019-12-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(choices=[(1, '10th'), (2, '12th'), (3, 'undergraduate'), (4, 'graduate')], default=1, max_length=150),
        ),
    ]
