# Generated by Django 3.0 on 2019-12-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191227_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('undergraduate', 'undergraduate'), ('graduate', 'graduate')], default=1, max_length=150),
        ),
    ]
