# Generated by Django 3.0 on 2019-12-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_awards_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_exp',
            old_name='job_des',
            new_name='job_description',
        ),
    ]
