# Generated by Django 3.0 on 2019-12-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191227_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillset',
            old_name='skill_text',
            new_name='skill_name',
        ),
    ]
