# Generated by Django 3.0 on 2019-12-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermidate', 'Intermidate'), ('Beginner', 'Beginner')], default=3, max_length=32),
        ),
    ]
