# Generated by Django 3.0 on 2019-12-27 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191227_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_team_size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
