# Generated by Django 3.0 on 2019-12-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
