# Generated by Django 3.0 on 2019-12-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='level',
            field=models.IntegerField(choices=[(1, 'Advanced'), (2, 'Intermidate'), (3, 'Beginner')], default=3),
        ),
    ]
