# Generated by Django 3.0 on 2019-12-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191228_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermidate', 'Intermidate'), ('Beginner', 'Beginner')], default=3, max_length=32),
        ),
    ]
