# Generated by Django 3.0 on 2019-12-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191231_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position_of_reponsiblity',
            old_name='positon',
            new_name='position',
        ),
    ]
