# Generated by Django 3.0 on 2020-01-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191231_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anon', models.BooleanField(default=False)),
                ('receiver_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver_profile', to='core.Profile')),
                ('sender_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_profile', to='core.Profile')),
            ],
        ),
    ]
