# Generated by Django 3.0 on 2020-01-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
