# Generated by Django 3.0 on 2020-01-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_messages_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_exp',
            name='company_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
