# Generated by Django 3.0 on 2020-01-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_work_exp_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_exp',
            name='company_location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
