# Generated by Django 3.0 on 2020-01-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_education_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
