# Generated by Django 3.0 on 2020-01-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_education_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_exp',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='work_exp',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
