# Generated by Django 3.0 on 2020-01-03 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200103_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_exp',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 20, 27, 23, 977879), null=True),
        ),
    ]
