# Generated by Django 3.0 on 2020-01-10 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200103_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_exp',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 14, 50, 26, 434490), null=True),
        ),
    ]
