# Generated by Django 3.0 on 2020-01-10 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200110_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receiver_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_profile', to='core.Profile'),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 15, 2, 49, 874499), null=True),
        ),
    ]
