# Generated by Django 3.0 on 2020-01-10 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200110_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time_of_message',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 15, 25, 0, 234433), null=True),
        ),
    ]
