# Generated by Django 3.0 on 2020-01-15 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200110_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_exp',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 9, 32, 24, 336977), null=True),
        ),
    ]
